<?php

namespace App\Controller\Admin;

use App\EasyAdmin\Fields\MultipleImageField;
use App\EasyAdmin\Fields\ImageUploadHelper;
use App\EasyAdmin\Helpers\ActionHelper;
use App\Entity\PortfolioPhotos;
use App\Repository\PortfolioPhotosRepository;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\BatchActionDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\HttpFoundation\Response;

class PortfolioPhotosCrudController extends AbstractCrudController
{
    private PortfolioPhotosRepository $photosRepository;
    private ImageUploadHelper $uploadHelper;
    private ActionHelper $actionHelper;

    public static function getEntityFqcn(): string
    {
        return PortfolioPhotos::class;
    }

    public function __construct(PortfolioPhotosRepository $photosRepository, ImageUploadHelper $uploadHelper, ActionHelper $actionHelper)
    {
        $this->photosRepository = $photosRepository;
        $this->uploadHelper = $uploadHelper;
        $this->actionHelper = $actionHelper;
    }

    public function configureActions(Actions $actions): Actions
    {
        return $this->actionHelper->changeActionsLabel($actions);
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)
            ->setPageTitle('index','Portfólio')
            ->setPageTitle('edit','Uprav fotografii')
            ->setPageTitle('new','Přidej fotografii');
    }

    public function configureFields(string $pageName): iterable
    {
        yield IdField::new('id')
            ->onlyOnIndex();

        yield ImageField::new('PortfolioPhotoName', 'Fotografie')
            ->hideWhenCreating()
            ->setBasePath('uploads/portfolioPhoto')
            ->setRequired(true)
            ->setUploadDir('public/uploads/portfolioPhoto');

        yield MultipleImageField::new('PortfolioPathFile', 'Fotka')
            ->setRequired(true)
            ->setFormTypeOption('multiple', true);

        yield AssociationField::new('photoCategory', 'Kategorie')
            ->setRequired(true)
            ->hideOnIndex()
            ->setFormTypeOption('choice_label', 'categoryName');

        yield TextField::new('photoCategoryName', 'Kategorie')
            ->onlyOnIndex();

        yield TextField::new('portfolioAlt', 'Alternativní text fotky')
            ->onlyWhenUpdating();
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $filesArray = parent::getContext()->getRequest()->files->get('PortfolioPhotos')['PortfolioPathFile'];
    
        foreach ($filesArray as $file) {
            $uniqueImageName = $this->uploadHelper->generateUniqueFileName($file->getClientOriginalName());
            $portfolioPhoto = new PortfolioPhotos();
            $portfolioPhoto
                ->setPhotoCategory($entityInstance->getPhotoCategory())
                ->setPortfolioAlt($entityInstance->getPhotoCategory()->getCategoryName())
                ->setPortfolioPhotoName($uniqueImageName);
    
            $this->uploadHelper->upload($file, $uniqueImageName, 'uploads/portfolioPhoto');
            $entityManager->persist($portfolioPhoto);
        }
    
        $entityManager->flush();
    }
    

    public function batchDelete(AdminContext $context, BatchActionDto $batchActionDto): Response
    {
        foreach ($batchActionDto->getEntityIds() as $entityId) {
            $entityToRemove = $this->photosRepository->find($entityId);
            $reviewToRemovePath = $entityToRemove->getPortfolioPhotoPath();
            $this->uploadHelper->deletePhotoFromDirectory($reviewToRemovePath);
        }
        return parent::batchDelete($context, $batchActionDto); // TODO: Change the autogenerated stub
    }

    public function delete(AdminContext $context): Response
    {
        $imgPath = $context->getEntity()->getInstance()->getPortfolioPhotoPath();
        $this->uploadHelper->deletePhotoFromDirectory($imgPath);
        return parent::delete($context); // TODO: Change the autogenerated stub
    }
}
